apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pdnd-interop-uservice-party-process
  name: pdnd-interop-uservice-party-process
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: pdnd-interop-uservice-party-process
  template:
    metadata:
      labels:
        app: pdnd-interop-uservice-party-process
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: pdnd-interop-uservice-party-process
          image: {{ .Values.containerRegistry }}/{{ .Values.imageRepository }}
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /ready
              port: management
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 20
          ports:
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: http
              containerPort: 8088
              protocol: TCP
            - name: monitoring
              containerPort: 9095
              protocol: TCP
          envFrom:
            - secretRef:
                name: application-insights
            - secretRef:
                name: contracts-storage
            - secretRef:
                name: mail
            - configMapRef:
                name: uservice-party-process
      volumes:
        - name: snapshots-volume
          emptyDir: {}