image:
  repository: selcpacr.azurecr.io/uservicepartyprocess
  pullPolicy: Always # TODO change me in IfNotPresent when each build will have a different tag
  tag: 0.1.41

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://selfcare.pagopa.it"

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_OPTS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  REQUIRED_CONTACT_POINT_NR: "1"
  USER_REGISTRY_MANAGEMENT_URL: "https://api.pdv.pagopa.it/user-registry/v1"
  MAIL_ONBOARDING_CONFIRMATION_LINK: "https://selfcare.pagopa.it/onboarding/confirm?jwt="
  MAIL_ONBOARDING_REJECTION_LINK: "https://selfcare.pagopa.it/onboarding/cancel?jwt="
  PRODUCT_MANAGEMENT_URL: https://api.selfcare.pagopa.it/external/v1
  SIGNATURE_VALIDATION_ENABLED: "true"
  CONFIRM_TOKEN_TIMEOUT: "90 seconds"
  ONBOARDING_SEND_EMAIL_TO_INSTITUTION: "true"
  ADDRESS_EMAIL_NOTIFICATION_ADMIN: "pectest@pec.pagopa.it"
  SELFCARE_ADMIN_NOTIFICATION_URL: "https://selfcare.pagopa.it/dashboard/admin/onboarding/"
