image:
  repository: selcuacr.azurecr.io/uservicepartyprocess
  tag: 0.1.49

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://uat.selfcare.pagopa.it,http://localhost:3000"

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_OPTS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  REQUIRED_CONTACT_POINT_NR: "1"
  USER_REGISTRY_MANAGEMENT_URL: "https://api.uat.pdv.pagopa.it/user-registry/v1"
  MAIL_ONBOARDING_CONFIRMATION_LINK: "https://uat.selfcare.pagopa.it/onboarding/confirm?jwt="
  MAIL_ONBOARDING_REJECTION_LINK: "https://uat.selfcare.pagopa.it/onboarding/cancel?jwt="
  PRODUCT_MANAGEMENT_URL: https://api.uat.selfcare.pagopa.it/external/v1
  SIGNATURE_VALIDATION_ENABLED: "true"
  CONFIRM_TOKEN_TIMEOUT: "90 seconds"
  ONBOARDING_SEND_EMAIL_TO_INSTITUTION: "false"
  SELFCARE_ADMIN_NOTIFICATION_URL: "https://uat.selfcare.pagopa.it/dashboard/admin/onboarding/"
  GEO_TAXONOMY_URL: "https://api.dev.selfcare.pagopa.it/external"
  MAIL_ONBOARDING_URL: "https://uat.selfcare.pagopa.it/onboarding/"

  # PagoPa signature feature
  # TODO set PROD values and enable it
  PAGOPA_SIGNATURE_ENABLED: "false"
  # TODO set with CEO name and surname
  PAGOPA_SIGNATURE_SIGNER: "PagoPA S.P.A."
  ARUBA_SIGN_SERVICE_BASE_URL: "https://arss.demo.firma-automatica.it:443/ArubaSignService/ArubaSignService"
  ARUBA_SIGN_SERVICE_IDENTITY_TYPE_OTP_AUTH: "demoprod"
  ARUBA_SIGN_SERVICE_IDENTITY_OTP_PWD: "dsign"
  ARUBA_SIGN_SERVICE_IDENTITY_USER: "titolare_aut"
  ARUBA_SIGN_SERVICE_IDENTITY_DELEGATED_USER: "delegato"
  ARUBA_SIGN_SERVICE_IDENTITY_DELEGATED_PASSWORD: "password11"
  ARUBA_SIGN_SERVICE_IDENTITY_DELEGATED_DOMAIN: "demoprod"