image:
  repository: selcdacr.azurecr.io/uservicepartyprocess
  tag: 0.1.44

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dev.selfcare.pagopa.it,http://localhost:3000"

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_OPTS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  REQUIRED_CONTACT_POINT_NR: "1"
  USER_REGISTRY_MANAGEMENT_URL: "https://api.uat.pdv.pagopa.it/user-registry/v1"
  MAIL_ONBOARDING_CONFIRMATION_LINK: "https://dev.selfcare.pagopa.it/onboarding/confirm?jwt="
  MAIL_ONBOARDING_REJECTION_LINK: "https://dev.selfcare.pagopa.it/onboarding/cancel?jwt="
  PRODUCT_MANAGEMENT_URL: "https://api.dev.selfcare.pagopa.it/external/v1"
  SIGNATURE_VALIDATION_ENABLED: "false"
  CONFIRM_TOKEN_TIMEOUT: "90 seconds"
  ONBOARDING_SEND_EMAIL_TO_INSTITUTION: "false"
  SELFCARE_ADMIN_NOTIFICATION_URL: "https://dev.selfcare.pagopa.it/dashboard/admin/onboarding/"
  GEO_TAXONOMY_URL: "https://api.dev.selfcare.pagopa.it/external"
