image:
  repository: selcuacr.azurecr.io/uservicepartyprocess
  tag: 0.1.54

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://uat.selfcare.pagopa.it,http://localhost:3000"

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_OPTS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  REQUIRED_CONTACT_POINT_NR: "1"
  USER_REGISTRY_MANAGEMENT_URL: "https://api.uat.pdv.pagopa.it/user-registry/v1"
  MAIL_ONBOARDING_CONFIRMATION_LINK: "https://uat.selfcare.pagopa.it/onboarding/confirm?jwt="
  MAIL_ONBOARDING_REJECTION_LINK: "https://uat.selfcare.pagopa.it/onboarding/cancel?jwt="
  PRODUCT_MANAGEMENT_URL: https://api.uat.selfcare.pagopa.it/external/v1
  SIGNATURE_VALIDATION_ENABLED: "true"
  CONFIRM_TOKEN_TIMEOUT: "90 seconds"
  ONBOARDING_SEND_EMAIL_TO_INSTITUTION: "false"
  SELFCARE_ADMIN_NOTIFICATION_URL: "https://uat.selfcare.pagopa.it/dashboard/admin/onboarding/"
  GEO_TAXONOMY_URL: "https://api.dev.selfcare.pagopa.it/external/geo-tax"
  MAIL_ONBOARDING_URL: "https://uat.selfcare.pagopa.it/onboarding/"

  # PagoPa signature feature
  # TODO set PROD values and enable it, it will require at least version 0.1.50
  PAGOPA_SIGNATURE_ENABLED: "false"
  # Used only if the certifate doesn't contain it
  PAGOPA_SIGNATURE_SIGNER: "PagoPA S.p.A."
  ARUBA_SIGN_SERVICE_BASE_URL: "https://asbr-pagopa.arubapec.it/ArubaSignService/ArubaSignService"
  ARUBA_SIGN_SERVICE_IDENTITY_TYPE_OTP_AUTH: "faPagoPa"
  ARUBA_SIGN_SERVICE_IDENTITY_OTP_PWD: "dsign"
  ARUBA_SIGN_SERVICE_IDENTITY_DELEGATED_DOMAIN: "faPagoPa"